<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>AlquilerVehiculos</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>AlquilerVehiculos</name>

    <modules>
        <module>eureka</module>
        <module>usuario</module>
        <module>cliente</module>
        <module>vendedor</module>
        <module>vehiculo</module>
        <module>disponibilidad</module>
        <module>reserva</module>
        <module>pago</module>
        <module>alquiler</module>
        <module>inspeccion</module>
        <module>multa</module>
        <module>gateway</module>
    </modules>
</project>
