server:
  port: 9000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
    url: /api/vendedores/v3/api-docs
    urls:
      - name: usuario
        url: /api/usuarios/v3/api-docs
      - name: cliente
        url: /api/clientes/v3/api-docs
      - name: vendedor
        url: /api/vendedores/v3/api-docs
      - name: vehiculo
        url: /api/vehiculos/v3/api-docs
      - name: disponibilidad
        url: /api/disponibilidad/v3/api-docs
      - name: inspeccion
        url: /api/inspecciones/v3/api-docs
      - name: alquiler
        url: /api/alquiler/v3/api-docs
      - name: pago
        url: /api/pago/v3/api-docs
      - name: reserva
        url: /api/reserva/v3/api-docs
      - name: multa
        url: /api/multa/v3/api-docs

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: usuario
              uri: http://localhost:9091
              predicates:
                - Path=/api/usuarios/**
            - id: cliente
              uri: http://localhost:9092
              predicates:
                - Path=/api/clientes/**
            - id: vendedor
              uri: http://localhost:9093
              predicates:
                - Path=/api/vendedores/**
            - id: vehiculo
              uri: http://localhost:9094
              predicates:
                - Path=/api/vehiculos/**
            - id: disponibilidad
              uri: http://localhost:9095
              predicates:
                - Path=/api/disponibilidad/**
            - id: inspeccion
              uri: http://localhost:9096
              predicates:
                - Path=/api/inspecciones/**
            - id: alquiler
              uri: http://localhost:9097
              predicates:
                - Path=/api/alquiler/**
            - id: pago
              uri: http://localhost:9098
              predicates:
                - Path=/api/pago/**
            - id: reserva
              uri: http://localhost:9099
              predicates:
                - Path=/api/reserva/**
            - id: multa
              uri: http://localhost:9100
              predicates:
                - Path=/api/multa/**
