spring.application.name=multa

# MySQL (ajustar host/puerto/credenciales al configurar Docker)
spring.datasource.url=jdbc:mysql://localhost:3306/multa_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto del microservicio
server.port=9100

# Swagger / OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html